# Generated by Django 5.1.7 on 2025-03-14 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_annual_revenue_customer_business_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskassessment',
            options={'get_latest_by': 'assessment_date'},
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Date when the customer was added to the system'),
        ),
    ]
